public with sharing class ITCompany 
{
    public Static List<Human> onBoardEmployees()
    {
      List<Human> emp =new List<Human>();
      Human emp1 = new Human('Harini' , 'Harini@gmail.com', 20 , 'female');
      emp.add(emp1);
      
      Human emp2 = new Human('Muthu' , 'Muthu@gmail.com', 25 , 'male');
      emp.add(emp2);

      Human emp3 = new Human('Diviya' , 'diviya@gmail.com', 24 , 'female');
      emp.add(emp3);

      Human emp4 = new Human('Priya' , 'priya@gmail.com', 25 , 'female');
      emp.add(emp4);

      Human emp5 = new Human('Keerthana' , 'keerthana@gmail.com', 26 , 'female');
      emp.add(emp5);

      Human emp6 = new Human('Rego' , 'rego@gmail.com', 33 , 'male');
      emp.add(emp6);

      Human emp7 = new Human('Sagana' , 'Sagana@gmail.com', 29 , 'female');
      emp.add(emp7);

      Human emp8 = new Human('Naveen' , 'Naveen@gmail.com', 30 , 'male');
      emp.add(emp8);

      Human emp9 = new Human('karan' , 'karan@gmail.com', 25 , 'male');
      emp.add(emp9);

      Human emp10 = new Human('Varsha' , 'Varsha@gmail.com', 27 , 'female');
      emp.add(emp10);

      Human emp11 = new Human('Arun' , 'arun@gmail.com', 25 , 'male');
      emp.add(emp11);

      Human emp12 = new Human('Siva' , 'siva@gmail.com', 35 , 'male');
      emp.add(emp12);

      Human emp13 = new Human('pavi' , 'pavi@gmail.com', 22, 'female');
      emp.add(emp13);

      Human emp14 = new Human('Logu' , 'logu@gmail.com', 21 , 'male');
      emp.add(emp14);

      Human emp15 = new Human('pooja' , 'pooja@gmail.com', 23 , 'female');
      emp.add(emp15);

      Human emp16 = new Human('Ragul' , 'ragul@gmail.com', 29 , 'male');
      emp.add(emp16);

      Human emp17 = new Human('Baskar' , 'baskar@gmail.com', 30 , 'male');
      emp.add(emp17);

      Human emp18 = new Human('Manju' , 'manju@gmail.com', 25 , 'female');
      emp.add(emp18);

      Human emp19 = new Human('subha' , 'subha@gmail.com', 30 , 'female');
      emp.add(emp19);

      Human emp20 = new Human('saravanan' , 'saravanan@gmail.com', 31 , 'male');
      emp.add(emp20);
      
      return emp;d
}
}